apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: project
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql"
